### ISSUE TITLE
bad class file

### ISSUE THREAD

**Issue by dchmelik** [hoehermann/purple-signal#9]
Even over a year later INSTALL.md has incomplete instructions but some days after trying I looked here, found issue where instructions are.
    On Slackware64 15.1+current w/jdk11-11.0.14-x86_64-1_SB the below happens.

```
d@cosmos:~/math/src/network/chat/bitlbee/plugins/1Slackware/purple-signal/build$ cmake --build .
[  4%] Building Java objects for purple_signal.jar
src/de/hehoe/purple_signal/PurpleSignal.java:17: error: cannot access AttachmentInvalidException
import org.asamk.signal.manager.AttachmentInvalidException;
                               ^
  bad class file: /home/d/math/src/network/chat/bitlbee/plugins/1Slackware/purple-signal/build/signal-cli-0.8.0/lib/lib.jar(org/asamk/signal/manager/AttachmentInvalidException.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
gmake[2]: *** [java/CMakeFiles/purple_signal.dir/build.make:89: java/CMakeFiles/purple_signal.dir/java_compiled_purple_signal] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:117: java/CMakeFiles/purple_signal.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by hoehermann** [comment]
Hi David

Thank you for your interest in this plug-in. I am sorry that this piece of free-to-use software I developed does not live up to your expectations. Please note that I am very eager to receive recommendations of what I should be doing in my spare time and will gladly update the status of dead projects on a daily basis. Yes, this project is dead. I have put many weeks of my life into this plug-in, but ultimately Signal removed support for this kind of shenanigans. Please see [this comment](https://github.com/hoehermann/purple-signal/issues/8#issuecomment-984579314) for a more detailed description.

As for the missing build instructions: I answered the question in #2. For your convenience, I updated the readme so the instructions can be found more easily.

To the issue itself:

> bad class file: (…) class file has wrong version 55.0, should be 52.0

According to [the class File Format](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.1-200-B.2), you are trying to load a Java 11 class file into a Java 8 VM. Java 8 is too old for signal-cli. The most recent version even needs Java 17.

Kind Regards
Hermann
